### ISSUE TITLE
Check optimallity of loadData.py

### ISSUE THREAD

**Issue by panos-span** [panos-span/neo4j#1]
The loadData.py script takes to long to execute, it took me 1.5 hours to complete. We need to optimize it somehow. @NataliaSpartinou will do the quality assurance.

**Comment by panos-span** [comment]
@NataliaSpartinou , it is worth noting that the import of the data can be done using commands from the neo4j terminal. It is not mandatory to use python.

**Comment by panos-span** [comment]
Problem with optimize file. We might have to switch back to the old one. Thanks for noticing @manosdell

**Comment by manosdell** [comment]
Spectacular job @NataliaSpartinou !!!
