### ISSUE TITLE
Check cypher queries

### ISSUE THREAD

**Issue by panos-span** [panos-span/neo4j#3]
## Evaluation of the neo4j queries is necessary and they also should be benchmarked in a way:
- [x]  Trough screenshots of running on neo4j client

**Comment by manosdell** [comment]
I think the second option is better

**Comment by panos-span** [comment]
It has been decided then. @NataliaSpartinou feel free as well to run the queries in your neo4j browser.

**Comment by panos-span** [comment]
@NataliaSpartinou thank you for your evaluation
